<?php

namespace App\Constants;

class AssetConsts
{

  const ASSET_APP_KEY = "ASSETS";

  const ASSET_AMOUNT = "ASSET_AMOUNT";
  const ASSET_BRAND  = "ASSET_BRAND";
  const ASSET_GROUP = "ASSET_GROUP";
  const ASSET_MAINTENANCE_FREQUENCE = "ASSET_MAINTENANCE_FREQUENCE";

  const ASSET_DEPRECIATION = "ASSET_DEPRECIATION";
  const ASSET_REVALUATION = "ASSET_REVALUATION";

  const ASSET_ASSIGNED = "ASSET_ASSIGNED";
  const ASSET_DECOMMISSIONED = "ASSET_DECOMMISSIONED";
  const ASSET_UNASSIGNED = "ASSET_UNASSIGNED";
  const ASSET_DEPRECATION_RESIDUAL_VALUE = "ASSET_DEPRECATION_RESIDUAL_VALUE";

  const ASSET_UPDATE_COST_IN_PROCESS = "ASSET_UPDATE_COST_IN_PROCESS";
  const ASSET_UPDATE_COST_EXECUTED = "ASSET_UPDATE_COST_EXECUTED";
  const ASSET_UPDATE_COST_REVERSED = "ASSET_UPDATE_COST_REVERSED";
  const ASSET_UPDATE_COST_CANCELLED = "ASSET_UPDATE_COST_CANCELLED";


  const ASSET_MESSAGE_EDIT_ERROR = "Error al consultar el activo";
  const ASSET_MESSAGE_STORE_LOG = "Creación de activo fijo";
  const ASSET_MESSAGE_STORE_SUCCESS = "Activo fijo creado correctamente - Nº de activo: ";
  const ASSET_MESSAGE_UPDATE_LOG = "Actualización de activo fijo";
  const ASSET_MESSAGE_UPDATE_SUCCESS = "Activo actualizado correctamente";
}
