<?php

namespace App\Constants;

class AuthConsts
{
    const AUTH_APP_KEY = "AUTH";
    const AUTH_USER_STATUS_ACTIVE = "USER_STATUS_ACTIVE";
    const AUTH_USER_STATUS_INACTIVE = "USER_STATUS_INACTIVE";
    const AUTH_USER_STATUS_LOCKED = "USER_STATUS_LOCKED";

    const USER_ROLE_ADMIN = "USER_ROLE_ADMIN";
    const USER_ROLE_APPROVER = "USER_ROLE_APPROVER";
    const USER_ROLE_RESPONSIBLE = "USER_ROLE_RESPONSIBLE";
}
