<?php

namespace App\Constants;

class CertificateConsts
{
  const CERTIFICATE_APP_KEY = "CERTIFICATE";

  const CERTIFICATE_ACTIVE = "CERTIFICATE_ACTIVE";
  const CERTIFICATE_APPROVED = "CERTIFICATE_APPROVED";
  const CERTIFICATE_CANCELLED = "CERTIFICATE_CANCELLED";
  const CERTIFICATE_CHECKING = "CERTIFICATE_CHECKING";
  const CERTIFICATE_IN_PROCESS = "CERTIFICATE_IN_PROCESS";
  const CERTIFICATE_INACTIVE = "CERTIFICATE_INACTIVE";
  const CERTIFICATE_REJECTED = "CERTIFICATE_REJECTED";
  const CERTIFICATE_SIGNATURE_PROCESS = "CERTIFICATE_SIGNATURE_PROCESS";
}
