<?php

namespace App\Constants;

class CertificateConsts
{
  const CERTIFICATE_APP_KEY = "CERTIFICATES";

  const CERTIFICATE_ACTIVE = "CERTIFICATE_ACTIVE";
  const CERTIFICATE_APPROVED = "CERTIFICATE_APPROVED";
  const CERTIFICATE_CANCELLED = "CERTIFICATE_CANCELLED";
  const CERTIFICATE_CHECKING = "CERTIFICATE_CHECKING";
  const CERTIFICATE_IN_PROCESS = "CERTIFICATE_IN_PROCESS";
  const CERTIFICATE_INACTIVE = "CERTIFICATE_INACTIVE";
  const CERTIFICATE_REJECTED = "CERTIFICATE_REJECTED";
  const CERTIFICATE_SIGNATURE_PROCESS = "CERTIFICATE_SIGNATURE_PROCESS";

  const CERTIFICATES_ASSET_STATUS = "CERTIFICATES_ASSET_STATUS";

  const CERTIFICATE_MESSAGE_STORE_SUCCESS = "Generación de acta de movimiento";
  const CERTIFICATE_MESSAGE_UPDATE_SUCCESS = "Actualización de acta de movimiento";
}
