<?php

namespace App\Constants;

class DerecognitionConsts
{
  const DERECOGNITION_APP_KEY = "DERECOGNITIONS";

  const DERECOGNITION_MESSAGE_STORE_LOG = "Creación de proceso de baja de activos";
  const DERECOGNITION_MESSAGE_STORE_SUCCESS = "Proceso de baja de activos iniciado correctamente";
  const DERECOGNITION_MESSAGE_UPDATE_LOG = "Actualización de proceso de baja de activos";
  const DERECOGNITION_MESSAGE_UPDATE_SUCCESS = "Proceso de baja de activos actualizado correctamente";
  const DERECOGNITION_UPDATE_STATUS_LOG = "Actualización de estado";
  const DERECOGNITION_UPDATE_STATUS_SUCCESS = "Estado actualizado correctamente";

  const DERECOGNITION_IN_PROCESS = "DERECOGNITION_IN_PROCESS";
  const DERECOGNITION_CHECKING = "DERECOGNITION_CHECKING";
  const DERECOGNITION_APPROVED = "DERECOGNITION_APPROVED";
  const DERECOGNITION_REJECTED = "DERECOGNITION_REJECTED";
  const DERECOGNITION_EXECUTED = "DERECOGNITION_EXECUTED";
  const DERECOGNITION_REVERSED = "DERECOGNITION_REVERSED";
  const DERECOGNITION_CANCELLED = "DERECOGNITION_CANCELLED";

  const DERECOGNITION_REASONS = "DERECOGNITION_REASONS";
}
