<?php

namespace App\Constants;

class GeneralConsts
{
  const DEPARTMENTS = "DEPARTMENTS";
  const IVA = "IVA";
  const PAYMENT_METHODS = "PAYMENT_METHODS";

  const COMPANY_ADDRESS = "COMPANY_ADDRESS";
  const COMPANY_AREAS = "COMPANY_AREAS";
  const COMPANY_CITY_ID = "COMPANY_CITY_ID";
  const COMPANY_DOCUMENT_NUMBER = "COMPANY_DOCUMENT_NUMBER";
  const COMPANY_NAME = "COMPANY_NAME";
  const COMPANY_PHONE_NUMBER = "COMPANY_PHONE_NUMBER";
}
